name: Deploy on Yandex.Cloud

on:
  push:
    branches:
      - master

jobs:

  deployment:
    name: Updating server repo
    runs-on: ubuntu-latest
    environment: HSEDAQ_YaCloud
    steps:
      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          host: 51.250.24.35
          username: doktorkrab
          key: ${{ secrets.KEY }}
          script: |
            cd HSEDAQ
            git pull
            sudo systemctl restart HSEDAQ.service
